version: 2
updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "mix"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - ".github/actions/"
      - ".github/workflows/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "github-actions"
      - "dependencies"
